#!/usr/bin/env node
// One-time local setup for the admin console. Generates a random local admin
// password, writes only its PBKDF2 hash + a session secret into .env (which is
// gitignored), and prints the password so you can sign in. Safe to re-run — it
// won't overwrite existing admin credentials.

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const envPath = path.join(root, ".env");
const env = fs.existsSync(envPath) ? fs.readFileSync(envPath, "utf8") : "";

if (/^ADMIN_PASSWORD_HASH=/m.test(env) && /^ADMIN_SESSION_SECRET=/m.test(env)) {
  console.log(".env already has admin credentials — leaving them as-is.");
  console.log("Delete those two lines and re-run this to regenerate.");
  process.exit(0);
}

const password = "admin-" + crypto.randomBytes(4).toString("hex");
const iterations = 100_000;
const salt = crypto.randomBytes(16);
const dk = crypto.pbkdf2Sync(password, salt, iterations, 32, "sha256");
const hash = `pbkdf2$sha256$${iterations}$${salt.toString("base64")}$${dk.toString("base64")}`;
const secret = crypto.randomBytes(32).toString("base64");

const block =
  `\n# Local admin console credentials (generated by scripts/dev-setup.mjs)\n` +
  `ADMIN_PASSWORD_HASH='${hash}'\n` +
  `ADMIN_SESSION_SECRET='${secret}'\n`;
fs.appendFileSync(envPath, block);

console.log("✓ Wrote admin credentials to .env (gitignored — never committed).\n");
console.log("  Local admin password:  " + password + "\n");
console.log("Next:");
console.log("  docker compose -f docker-compose.local.yml up --build");
console.log("Then open http://localhost:8080/admin and sign in.");
